# Generated by Django 5.2.4 on 2025-08-02 09:39

import birthday.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(validators=[birthday.validator.real_age], verbose_name='Дата рождения'),
        ),
    ]
