# Generated by Django 5.2.4 on 2025-08-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='ff',
        ),
    ]
